language: objective-c
osx_image: xcode11.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - RUN_TESTS="YES"
    - BUILD_EXAMPLE="YES"
    - POD_LINT="NO"
    - POD_QUALITY_CHECK="NO"
  matrix:
    - DESTINATION="OS=13.2.2,name=iPhone 8 Plus"
script:
  - Scripts/travis-ci.sh