name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  LC_CTYPE: en_US.UTF-8
  LANG: en_US.UTF-8

jobs:
  test:
    name: Test on iOS  
    runs-on: macos-latest
        
    strategy:
      matrix:
        destination:
          - "OS=18.5,name=iPhone 16 Pro"
          - "OS=18.5,name=iPhone 16"
          - "OS=18.5,name=iPhone SE (3rd generation)"

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'
    
    - name: Install xcpretty
      run: gem install xcpretty
    
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show available simulators  
      run: xcrun simctl list devices available
      
    - name: Build Swift Package for iOS
      run: |
        set -o pipefail
        xcodebuild build \
          -scheme FDTake \
          -destination "${{ matrix.destination }}" | xcpretty
          
    - name: Test iOS Example App
      run: |
        set -o pipefail
        xcodebuild build \
          -project "iOS Example/iOS Example.xcodeproj" \
          -scheme "iOS Example" \
          -destination "${{ matrix.destination }}" | xcpretty

